branches:
  - main

tagFormat: "${version}"  # No "v" prefix

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - breaking: true
          release: major
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: refactor
          release: patch
        - type: build
          release: patch
        - type: ci
          release: patch
        - type: chore
          release: patch

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "âœ¨ Features"
          - type: fix
            section: "ðŸ› Bug Fixes"
          - type: perf
            section: "âš¡ Performance Improvements"
          - type: refactor
            section: "â™»ï¸ Code Refactoring"
          - type: build
            section: "ðŸ”§ Build System"
          - type: ci
            section: "ðŸ‘· CI/CD"
          - type: chore
            section: "ðŸ”¨ Chores"

  - - "@semantic-release/exec"
    - prepareCmd: "echo ${nextRelease.version} > .semantic-release-version"
      publishCmd: "echo 'Released version ${nextRelease.version}'"

  - - "@semantic-release/github"
    - failComment: false
      successComment: false
      labels: false
      assets: [ ]

  #- - "@semantic-release/changelog"
  #  - changelogFile: "CHANGELOG.md"

  #- - "@semantic-release/git"
  #  - assets:
  #      - "CHANGELOG.md"
  #    message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"