preset: conventionalcommits
branches:
  - main

tagFormat: "${version}"  # No "v" prefix

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: refactor
          release: patch
        - type: build
          release: patch
        - type: ci
          release: patch
        - type: chore
          release: patch

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "✨ Features"
          - type: fix
            section: "🐛 Bug Fixes"
          - type: perf
            section: "⚡ Performance Improvements"
          - type: refactor
            section: "♻️ Code Refactoring"
          - type: build
            section: "🔧 Build System"
          - type: ci
            section: "👷 CI/CD"
          - type: chore
            section: "🔨 Chores"

  - - "@semantic-release/github"
    - failComment: false
      successComment: false
      labels: false
      assets: [ ]

  #- - "@semantic-release/changelog"
  #  - changelogFile: "CHANGELOG.md"

  #- - "@semantic-release/git"
  #  - assets:
  #      - "CHANGELOG.md"
  #    message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"