dryRun: false
preset: extended
scheme: SEMVER
verbosity: INFO
releaseLenient: true
changelog:
  includeLatestRelease: true
  sections:
    "Features": "^feat.*$"
    "Fixes": "^fix.*$"
    "Maintenance": "^(build|chore|perf).*$"
    "Changes": "^refactor.*$"
    "Others": ".*"
  substitutions:
    "(?m)#([0-9]+)(?s)": "[#%s](https://github.com/RobinPcrd/compose-cupertino/issues/%s)"
    "(?m)\\[([a-z0-9]+)\\](?s)": "[[%s](https://github.com/RobinPcrd/compose-cupertino/commit/%s)]"
commitMessageConventions:
  enabled:
    - conventionalCommits
  items:
    conventionalCommits:
      # expression: "(?m)^(?<type>[a-zA-Z0-9_]+)(\\((?<scope>[a-z ]+)\\))?(!)?:( (?<title>.+))$(?s).*"
      bumpExpressions:
        major: "(?s)(?m)^[a-zA-Z0-9_]+(\([a-zA-Z0-9 \-_]+\))?(!: .*|.*^(BREAKING( |-)CHANGE: )).*"
        minor: "(?s)(?m)^feat(!{0})(\([a-zA-Z0-9 \-_]+\))?: (?!.*^(BREAKING( |-)CHANGE: )).*"
        patch: "(?s)(?m)^(build|chore|fix|perf|refactor)(?!!|.*^(BREAKING( |-)CHANGE: )).*"
releaseTypes:
  enabled:
    - mainline
    - release
  items:
    release:
      identifiers: [ ]
